### ISSUE TITLE
Translation of % to prover broken

### ISSUE THREAD

**Issue by danielgrahl** [janhaag/PSE2011#14]
The expression -1%2 is equal to -1 according to the definition of %. This is respected in runtime checking, but for the prover it is translated to 1. Check the following program:
main (){
   int x = -1%2;
}
ensure x==-1;

**Comment by ratefuchs** [comment]
The problem is that -1%2 is equal to 1 according to the definition of mod in SMTLib. Also, the definition of div differs from the more common definition where the result is rounded towards zero.
(Here a link where the behavior of div and mod in SMTLib is described: http://goedel.cs.uiowa.edu/smtlib/theories/Ints.smt2).

The interpreter was changed so that its "/" and "%" operators behave like the SMTLib operators "div" and "mod", respectivly.
