### ISSUE TITLE
wp for infinite recursions

### ISSUE THREAD

**Issue by danielgrahl** [janhaag/PSE2011#16]
Try to prove the following program. After a few miliseconds you will encounter the JVM's stack overflow.
int foo (int x) { return foo(x+1); }
main(){ int x = foo(0); }

**Comment by ratefuchs** [comment]
We decided to disallow function calls in return statements (it will be not syntactically correct) now since:
1. It is not needed (one could introduce a variable one statement before and return that variable)
2. One can't express something about the function call result in the following ensure (which is possible with a construct like 1.)
So this bug cannot happen anymore.
