### ISSUE TITLE
Incorrect handling of array bounds checking.

### ISSUE THREAD

**Issue by danielgrahl** [janhaag/PSE2011#7]
The following program is incorrect, but gives the misleading error message "parameter of length must be an array".
main () {
int[] a;
a[4] = 4;
}

**Comment by janhaag** [comment]
I changed this bug to reflect what's actually going on.

**Comment by ratefuchs** [comment]
The parser misses the array initialization and takes line 2 as a variable declaration.
So the length function that was automatically inserted before line 3 (because of the array read) gets problems...

This bug is fixed; the type checker now reports the missing array initializer with an appropriate error message.
