### ISSUE TITLE
Parser does not parse double operator correctly

### ISSUE THREAD

**Issue by linjin** [janhaag/PSE2011#79]
i = 5 ++ 5; and i = 5 - - 5; are parsed to i = 5 + 5; and i = 5 - 5; instead of throwing an error message as the parser does with double /, \* and %.

**Comment by ratefuchs** [comment]
-> "i = 5 ++ 5;" is correctly parsed to "i = 5 + 5;". It is interpreted as "i = 5 + (+ 5));", where the first "+" is an binary addition operator and the second one a unary plus operator, the latter is left out since it has no effect (since a = +a for all ints a).

-> "i = 5 - - 5;" is a similar case, except the unary "-" must not be left out. So it should parse to "i = 5 - (- 5);"; in fact, my version of the program does work correctly. (It also does with "i=5+-5;" and "i=5-+5;").

I will close the issue for now because I don't think there is a bug.
If "i = 5 - - 5;" is really parsed to "i = 5 - 5;", please reopen the issue.
